spring:
  application:
    name: TCM-Management-System
  docker:
    compose:
      file: Docker/tcm-docker-compose-deps.yml
      lifecycle-management: start_only
      profiles:
        active: dev
      enabled: false

  datasource:
    url: jdbc:mysql://tcm-mysql:3306/tcm_management_system
    username: root
    password: verySecret

  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none

  flyway:
    password: verySecret
    user: root
    url: jdbc:mysql://tcm-mysql:3306/tcm_management_system
    enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://tcm-eureka-server-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, conditions
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
